# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Propensity Score matching
#' @return A list.
#' @param x A numeric vector with probabilities
#' @examples
#' # Testing the function
#' x <- runif(10)
#' matching_subjects(x)
#' @export
matching_subjects <- function(x) {
    .Call(`_egpkg_matching_subjects`, x)
}

#' Hello world from Rcpp
#' @return A list with two vectors (`x`, `y`).
#' @examples
#' rcpp_hello_world()
#' @export
rcpp_hello_world <- function() {
    .Call(`_egpkg_rcpp_hello_world`)
}

