# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Match subjects Rcpp
#' @return A list with two vectors (`match_id`, `match_x`).
#' @param x NumericVector. This is the input
#' @examples
#' # Testing the function
#' library(Rcpp)
#' x = c(1,2,3,4,5,6)
#' matching_subjects(x)
#' @export
matching_subjects <- function(x) {
    .Call(`_egpkg_matching_subjects`, x)
}

#' Hello world from Rcpp
#' @return A list with two vectors (`x`, `y`).
#' @examples
#' rcpp_hello_world()
#' @export
rcpp_hello_world <- function() {
    .Call(`_egpkg_rcpp_hello_world`)
}

